### ISSUE TITLE
Humio error message spammed in logs

### ISSUE THREAD

**Issue by YassienW** [APXEOLOG/hnh-auto-mapper-server#3]
When no Humio credentials are provided, it keeps spamming this message every minute or so

`2020-03-02 11:22:26.494 ERROR 11312 --- [trics-publisher] io.micrometer.humio.HumioMeterRegistry   : failed to send metrics to humio: The resource requires authentication, which was not supplied with the request
`

**Comment by APXEOLOG** [comment]
Hi! Please try to add this line into `application.properties`:
`management.metrics.export.humio.enabled=false`

**Comment by YassienW** [comment]
That does it. Thanks!
